# Configuration for building documentation on Travis CI
# See https://travis-ci.org/ for more info.

---
language: python
python:
    - '3.7'

install:
    - pip install -e .[all]
    - npm install -g eslint

script:
    - pytest
    - pycodestyle .
    - eslint cylc/
    - make html linkcheck
