name: Release stage 1 - create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number (PEP 440 compliant e.g., 8.12.4, 8.0a2 etc)
        required: true
      branch:
        description: The branch to open the PR against
        required: false
        default: 'master'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Sanitise workflow inputs # Should be 1st step
      uses: cylc/release-actions/stage-1/sanitize-inputs@v1

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BASE_REF }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz
        pip install git+https://github.com/cylc/cylc-flow/  # install latest cylc-flow
        pip install -e .[all]

    - name: Create & checkout PR branch
      uses: cylc/release-actions/stage-1/checkout-pr-branch@v1

    - name: Set the package version
      uses: cylc/release-actions/stage-1/set-python-package-version@v1
      with:
        init-file: 'cylc/sphinx_ext/__init__.py'
        pypi-package-name: 'cylc-sphinx-extensions'

    - name: Test build
      uses: cylc/release-actions/build-python-package@v1

    - name: Test make HTML
      run: make html

    - name: Create pull request
      uses: cylc/release-actions/stage-1/create-release-pr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
