name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: eslint
        run: npx eslint .

      - name: configure python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          sudo apt-get install -y graphviz
          pip install git+https://github.com/cylc/cylc-flow/  # install latest cylc-flow
          pip install -e .[all]

      - name: pycodestyle
        run: |
          pycodestyle .
          npx eslint cylc/

      - name: unittest
        run: |
          pytest

      - name: build
        run: |
          make html slides linkcheck

      - name: debug
        if: failure()
        run: |
          cat /tmp/sphinx-err*  # sphinx traceback
