# THIS FILE IS PART OF THE CYLC SUITE ENGINE.
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: update copyright year

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 1 1 *' # Every Jan 1st @ 05:10 UTC

jobs:
  update-copyright:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout PR branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          year=$(date '+%Y' --utc)
          branch_name="copyright-${year}"
          git checkout -b "$branch_name"
          echo "YEAR=$year" >> $GITHUB_ENV
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Update copyright year
        env:
          README_FILE: 'README.rst'
        run: |
          pattern="(Copyright \(C\) 2008-)[0-9]{4}"
          sed -i -E "s/${pattern}/\1${YEAR}/" "$README_FILE"
        # Note this is not foolproof as the copyright notice might change

      - name: Commit & push
        run : |
          git commit -a -m "Update copyright year" -m "Workflow: ${{ github.workflow }}, run: ${{ github.run_number }}"
          git push origin "$BRANCH_NAME"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "authorization: Bearer ${GH_TOKEN}" \
            -H 'content-type: application/json' \
            --data '{
              "title": "Auto PR: update copyright year",
              "head": "${{ env.BRANCH_NAME }}",
              "base": "master",
              "body": "Happy new year!"
            }'
